# --- TABLE DE CORRESPONDANCE POUR LES INTERFACES ---
INTERFACE_MAP = {
    "wan": "WAN",
    "lan": "ADMINISTRATION",
    "opt1": "LAN",
    "opt2": "DMZ"
}

# --- TABLE DE CORRESPONDANCE POUR LES RESEAUX ---
NET_MAP = {
    "wan": "WAN SUBNET",
    "lan": "ADMINISTRATION SUBNET",
    "opt1": "LAN SUBNET",
    "opt2": "DMZ SUBNET"
}

# --- TABLE DE CORRESPONDANCE POUR LES NOMS DES ADRESSES ---
ADDRESS_MAP = {
    "wan:ip": "WAN ADDRESS",
    "lan:ip": "ADMINISTRATION ADDRESS",
    "opt1:ip": "LAN ADDRESS",
    "opt2:ip": "DMZ ADDRESS"
}

# --- SI UTILISATION D'ALIAS POUR LES PORTS ---
PORT_MAP = {
    "WEB_ACCESS": "80/443"
}